[package]
name = "clmm-router"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = { workspace = true }
soroban-token-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
clmm-factory = { path = "../factory" }
clmm-pool = { path = "../pool" }
clmm-position-manager = { path = "../position_manager" }

[lib]
crate-type = ["cdylib", "rlib"]
